# Generated by Django 3.2.4 on 2021-06-21 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='locomotive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locomotives', to='parsing.locomotive'),
        ),
        migrations.AlterField(
            model_name='locomotive',
            name='type_loc_el',
            field=models.BooleanField(verbose_name='is the electric traction'),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Sector name')),
                ('number', models.IntegerField(db_index=True, verbose_name='Sector number')),
                ('calcskew', models.FloatField(verbose_name='Calculation skew')),
                ('train', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trains', to='parsing.train')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'ordering': ['-calcskew'],
            },
        ),
    ]
