# Generated by Django 3.2.4 on 2021-07-01 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0003_auto_20210624_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sectors', to='parsing.train'),
        ),
    ]
