# Generated by Django 3.2.4 on 2021-08-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0004_alter_sector_train'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/uploaded_files', verbose_name='Files')),
                ('name', models.CharField(max_length=255, verbose_name='File name')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Uploaded datetime')),
            ],
        ),
    ]
